[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComputePipeline = "95dc2771-c249-4cd0-9c9f-1f3b4330693c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
MakieTeX = "6d554a22-29e7-47bd-aee5-0c5f06619414"
PNGFiles = "f57f5aa1-a3ce-4bc8-8ab9-96f992907883"
PixelMatch = "433bd86c-62cb-491d-a348-72c5c8365002"
tectonic_jll = "d7dd28d6-a5e6-559c-9131-7eb760cdacc5"

[sources]
MakieTeX = {path = ".."}
Makie = {url = "https://github.com/MakieOrg/Makie.jl.git", rev = "jk/glyph-buffer-refactor", subdir = "Makie"}
CairoMakie = {url = "https://github.com/MakieOrg/Makie.jl.git", rev = "jk/glyph-buffer-refactor", subdir = "CairoMakie"}
ComputePipeline = {url = "https://github.com/MakieOrg/Makie.jl.git", rev = "jk/glyph-buffer-refactor", subdir = "ComputePipeline"}

[compat]
julia = "1.12"
